### ISSUE TITLE
Issues when using R

### ISSUE THREAD

**Issue by thadryanjs** [luk400/vim-jukit#93]
Hello!

This is probably the slickest developer experience I've seen for Python data science in neovim. Thanks for your work on it.

I am able to get this working smoothly with Python, but can't recreate it using R.

I've created an ipynb that's running R code correctly.

I then run:
```
let g:jukit_shell_cmd='radian'
```
or:
```
let g:jukit_shell_cmd='R'
```

I open the file in neovim and hit `<leader>np` per the docs. I got the following message:
```
"test-R.ipynb" 100L, 5112B written
Error detected while processing function jukit#convert#notebook_convert[5]..<SNR>95_convert_to_script[12]..provider#python3#Call:
line   18:
Error invoking 'python_execute' on channel 12 (python3-script-host):
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "/home/thadryan/.local/share/nvim/lazy/vim-jukit/helpers/ipynb_convert/convert.py", line 120, in convert
    language, nb = get_nb_and_language(nb, lang)
  File "/home/thadryan/.local/share/nvim/lazy/vim-jukit/helpers/ipynb_convert/util.py", line 28, in get_nb_and_language
    lang_dict.get(language) is not None
AssertionError: Language `R` not supported
Press ENTER or type command to continue
```

Neovim:
```
NVIM v0.9.2
Build type: Release
LuaJIT 2.1.1694285958

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/share/nvim"

Run :checkhealth for more info
```

Can you point me in the right direction in terms of debugging this?

Thanks again.

**Comment by luk400** [comment]
Hi, please try again, should be fixed now

**Comment by thadryanjs** [comment]
> should

Good to go, thank you!
